services:
  scraper:
    image: ruby-scraper:latest
    build: .
    container_name: ruby-scraper
    environment:
      - API_URL=http://api:4567
    depends_on:
      api:
        condition: service_healthy
  api: &server
    image: sinatra-api:latest
    build: api
    container_name: sinatra-api
    ports:
      - 4567:4567
    healthcheck:
      test: ["CMD", "curl", "localhost:4567"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
    environment:
      MONGODB_URI: mongodb://data-sink:27017/posts
    depends_on:
      - data-sink
  data-sink:
    image: mongo:7.0.5-rc0-jammy
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - .mongodb/data:/data/db
  test-server:
    <<: *server
    container_name: test-server
    ports:
      - 4444:4444
    volumes:
      - ./__tests__:/test
    command: bash -c "cd /test && ruby test_server.rb -e playtime -p 4444"
